Minor QOL improvements I desired
noscript/elevator.vim pull request #5
Opened 2024-02-18 03:09 UTC by b0dee

Addressed a number of improvements I desired: 

- [x] Launch on start
- [x] Toggle scroll bar
- [x] Customise highlight group 
- [ ] Fix lag when scrolling by line (i.e. holding down J/K)

2024-02-19 11:17 UTC, noscript commented
Thanks for the PR. Could you please also add new variables and command to the documentation?

2024-02-19 21:49 UTC, b0dee commented
Documentation updated, thanks for accepting it and great work on the plugin!

2024-02-20 01:28 UTC, b0dee commented
Submitted another as noticed the scroll bar wouldn't reach end of window until topline == last line in file
It will now put it to bottom of screen the moment the last line of file is on the window (if it wasn't going to already, not sure if edge case but happened a bit in files I was testing on)

2024-02-20 18:45 UTC, noscript requested changes

2024-02-20 18:45 UTC, noscript commented on autoload/elevator.vim
> +  g:elevator#width = v:false
This condition unnecessary. Besides it breaks the compilation as `g:elevator#width` is boolean.

2024-02-20 18:45 UTC, noscript commented on autoload/elevator.vim
> +  g:elevator#hidden = v:false
Please use `false`.

2024-02-20 18:45 UTC, noscript commented on autoload/elevator.vim
> +    g:elevator#hidden = v:false
`true`, `false`. Optionally `g:elevator#hidden = !g:elevator#hidden`

2024-02-20 18:45 UTC, noscript commented on doc/elevator.txt
> +*g:elevator#highlight*                Set the highlight group for the scroll bar
Please put `.` at the end of sentences, for consistency with the rest of documentation.

2024-02-20 18:45 UTC, noscript commented on plugin/elevator.vim
> +	if exists('g:elevator#show_on_enter') && g:elevator#show_on_enter == v:true
`if exists('g:elevator#show_on_enter') && g:elevator#show_on_enter`

2024-02-20 18:45 UTC, noscript commented on autoload/elevator.vim
> +  endif
This change makes the scrollbar not move if buffer is scrolled below the last line, and then suddenly jump up when it's scrolled above the last line.

2024-02-20 18:48 UTC, noscript commented
> Submitted another as noticed the scroll bar wouldn't reach end of window until topline == last line in file It will now put it to bottom of screen the moment the last line of file is on the window (if it wasn't going to already, not sure if edge case but happened a bit in files I was testing on)

This is intended and follow the behavior of GVim scrollbars (`guioptions+=r`), because Vim allows to scroll the buffer past the last line.

2024-02-20 21:03 UTC, b0dee commented on autoload/elevator.vim
> +  g:elevator#width = v:false
Sorry - bug, should be g:elevator#show_on_enter = false
Fixed in next PR

2024-02-20 21:03 UTC, b0dee commented on autoload/elevator.vim
> +  g:elevator#hidden = v:false
Fixing in next PR

2024-02-20 21:47 UTC, b0dee commented on autoload/elevator.vim
> +    g:elevator#hidden = v:false
Neatened and used toggling boolean (!)
Fixes in next PR

2024-02-20 22:00 UTC, b0dee commented on doc/elevator.txt
> +*g:elevator#highlight*                Set the highlight group for the scroll bar
Resolved in next PR

2024-02-20 22:00 UTC, b0dee commented on plugin/elevator.vim
> +	if exists('g:elevator#show_on_enter') && g:elevator#show_on_enter == v:true
Fixed in next PR

2024-02-20 22:01 UTC, b0dee commented
Ahh - learn something new everyday. All changes completed submitting PR now

2024-12-21 17:23 UTC, noscript commented
I rebased and merged the remaining changes manually.

2024-12-21 17:23 UTC, closed without merging